default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: request-wsseas-people_development

test:
  <<: *default
  database: request-wsseas-people_test

production:
  <<: *default
  database: request-wsseas-people_production
  username: request-wsseas-people
password: <%= ENV['REQUEST-WSSEAD-PEOPLE_DATABASE_PASSWORD'] %>
